"""Entrypoint for the Lumina forecasting tree.

Usage:
    python -m lumina_forecasting.run_pipeline
    python -m lumina_forecasting.run_pipeline --excel path/to/Lumina_Markets_Dataset.xlsx
    python -m lumina_forecasting.run_pipeline --gemini        # add NL narrative
    python -m lumina_forecasting.run_pipeline --gemini-mock   # NL demo, no API key

Runs the full orchestrated tree and prints the summarizer's brief. With
--gemini (and GEMINI_API_KEY set) it also prints a natural-language narrative.
"""
from __future__ import annotations
import argparse

from . import config
from .orchestrator import run


def _mock_gemini(prompt: str) -> str:
    """Offline stand-in so the NL layer can be demoed without an API key."""
    return ("This run is healthy and its outputs can be trusted. The median "
            "forecasts are off by about 15% of total volume and the uncertainty "
            "bands cover roughly the intended share of actual sales, so the "
            "stated confidence is honest. Cross-product effects were handled "
            "correctly, the hierarchy reconciles exactly, and the inventory "
            "guidance stocks staples generously while holding perishables closer "
            "to expected demand. (Generated by a mock client for demonstration.)")


def main():
    ap = argparse.ArgumentParser(description="Lumina demand forecasting tree")
    ap.add_argument("--excel", default=None, help="Path to the dataset workbook")
    ap.add_argument("--no-persist", action="store_true", help="Do not write artifacts")
    ap.add_argument("--cold-start", action="store_true",
                    help="Also run a cold-start demo on a Strawberries-like new SKU")
    ap.add_argument("--gemini", action="store_true",
                    help="Add a Gemini natural-language narrative (needs GEMINI_API_KEY)")
    ap.add_argument("--gemini-mock", action="store_true",
                    help="Add a MOCK natural-language narrative (no API key needed)")
    args = ap.parse_args()

    new_sku = None
    if args.cold_start:
        new_sku = {"SKU_ID": "SKU0034", "Sub_Category": "Strawberries",
                   "Category": "Produce", "Brand_Tier": "Premium", "Perishability_Flag": 1}

    llm_client = None
    if args.gemini:
        config.LLM_ENABLED = True            # real Gemini call inside the summarizer
    elif args.gemini_mock:
        llm_client = _mock_gemini            # offline demonstration

    state = run(excel_path=args.excel, new_sku_attrs=new_sku,
                persist=not args.no_persist, llm_client=llm_client)

    summ = state["summary"]
    # deterministic first, NL second (combined already stitches them)
    print(summ.get("combined", summ["text"]))
    if summ.get("llm_error") and (args.gemini or args.gemini_mock):
        print(f"\n[note] LLM narrative unavailable: {summ['llm_error']}")
        print("       Deterministic summary shown above is unaffected.")


if __name__ == "__main__":
    main()
